### ISSUE TITLE
是否考虑弄个微信公众号，每周发布一下呢？

### ISSUE THREAD

**Issue by cycorey** [zenany/weekly#14]
订阅更方便，谢谢！

**Comment by zenany** [comment]
多谢建议:) 这份 Weekly 目前也通过 FEX 微信公众号在发布，可关注：

![erwei](https://cloud.githubusercontent.com/assets/2378632/15880295/65b36888-2d5e-11e6-8839-555e6981c25d.jpg)

但我觉得公众号发布的文章，其中链接点不开，看起来也不方便。其实对码农来说 GitHub 是非常不错的东西，watch 后有更新会主 mail 通过推送，在 dashborad 也能看到。

真要提升自己的技术视野和知识面的话，建议采用主动挖掘的模式，用 RSS 去订阅和阅读一些优秀站点，看一些专业书籍，逐步形成自己的知识库。目前在微信上传播的技术类文章，质量中等，有点快消品的感觉。推荐采用 Feedly 逐步完善自己的 RSS 源，在手机上可以用 gReader 阅读。

关于个人知识库的整理，可以参考：https://github.com/zenany/zenany.github.io/blob/master/_posts/about_time_and_knowledge_management.md 中 Weekly 如何整理的。希望对你有所帮助。

**Comment by cycorey** [comment]
谢谢！碎片时间一般在手机上，微信公众号中的文章的确良莠不齐，关于手机碎片时间如何利用好，您有些什么心得？

**Comment by zenany** [comment]
其实，我觉得碎片时间不要用在微信公众号上，真正的高质量知识还是需要看书的，书籍才是经得起考研的知识，文章传递的很多都是只需要知道即可，不管是技术的还是管理、甚至科学、哲学、设计、产品的都可以看。可以考虑看 pdf 形式的书或者 kindle 电子书，每天翻几页，一年也看好几本书呢。技术方面推荐我必然推荐新人的两本书： http://www.catb.org/esr/writings/taoup/  https://www.amazon.com/Linux-System-Programming-Talking-Directly/dp/1449339530 。最近出的 The Go Programming Language 和 Site Reliability Engineering: How Google Runs Production Systems 这两本书也非常不错。软件工程方面有本书非常值得看：邹欣老师的 构建之法 https://book.douban.com/subject/26577755/
