### ISSUE TITLE
2016.07.25 「Facebook的实时流处理技术」链接失效

### ISSUE THREAD

**Issue by iyaozhen** [zenany/weekly#15]
> Facebook的实时流处理技术
> http://toutiao.com/a6309016645101732098/
> 本文介绍了Facebook在设计该系统时从易用性、性能、容错、可伸缩性以及正确性等方面考虑所做的重要设计决策，这些决策和系统如何满足秒级的延迟需求，以及在构建该系统的过程中Facebook所总结的经验教训。

**Comment by zenany** [comment]
已经更新为 http://www.linuxidc.com/Linux/2016-07/133406.htm ，多谢提醒:)
