### ISSUE TITLE
这个列表里没有2017-12-18的更新

### ISSUE THREAD

**Issue by xiongwilee** [zenany/weekly#19]
https://github.com/zenany/weekly/tree/master/software/2017 这个列表里没有2017-12-18的更新

**Comment by zenany** [comment]
抱歉，本周一忘记更新了，刚刚补上就看到这个 issue 了。
如果后续发现可以早点提醒我:)

**Comment by xiongwilee** [comment]
写个脚本，更新blog之后自动commit，然后自动push
