### ISSUE TITLE
where is 2022 年度总结 >_<

### ISSUE THREAD

**Issue by xuwangzihao** [zenany/weekly#26]
在首页的 readme 文件里面，没有看到相关索引，期待更新

**Comment by zenany** [comment]
我加一下😄目前暂没有写一篇文档作为年终总结的习惯，语雀有不少用户在写，欢迎围观 https://www.yuque.com/search?q=2021+%E5%B9%B4%E5%BA%A6%E6%80%BB%E7%BB%93&type=content&scope=%2F&tab=public&p=1

**Comment by dawinSoft** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.Tobiasheitor, @adamnemecek, @qf345295, @stoksc, @NameYoung, @purplematter, @kapslocker, @Isilven, @thoughtstirring, @t1mursadykov, @Nezteb, @candfan, @dianwoshishi, @aemon, @jane35622, @BladeSun, @leeroybrun, @jemyzhang, @myfxyz, @jkljkm
