### ISSUE TITLE
Fullweb Weekly

### ISSUE THREAD

**Issue by nepsilon** [zenany/weekly#9]
Hi @zenany!

I'm Julien, I'm curating a weekly newsletter at [fullweb.io](http://fullweb.io) for Web Fullstack Developers.
Here is a sample: http://fullweb.io/archives/issue-14.html

Take a look and if you find it interesting feel free to subscribe and add it to your list!

Any suggestion to improve it very welcome!

— J

**Comment by shallker** [comment]
Nice newsletter!

**Comment by zenany** [comment]
@nepsilon :  fullweb.io is so wonderful, it is very useful for engineers, i've subscribed. I'll add good articles of fullweb.io to my weekly, and send it to my colleagues and friends. Thank you for supplying such excellent resources.

**Comment by zenany** [comment]
@nepsilon i aslo add fullweb.io and other weekly to README.md :)

**Comment by nepsilon** [comment]
@zenany Thanks! Very glad you like it. 🙌
